name: Deploy WordPress Theme

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows manual trigger

jobs:
  deploy:
    name: Deploy to WordPress Server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: PHP Syntax Check
      run: |
        echo "=== PHP Syntax Check Started ==="
        SYNTAX_ERRORS=0
        for file in $(find . -name "*.php"); do
          echo "Checking: $file"
          if ! php -l "$file"; then
            echo "❌ SYNTAX ERROR in: $file"
            SYNTAX_ERRORS=$((SYNTAX_ERRORS + 1))
          else
            echo "✅ OK: $file"
          fi
        done
        echo "=== PHP Syntax Check Complete ==="
        if [ $SYNTAX_ERRORS -gt 0 ]; then
          echo "❌ Found $SYNTAX_ERRORS PHP syntax errors"
          exit 1
        else
          echo "✅ All PHP files have valid syntax"
        fi

    - name: Deploy to server via SSH
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i"
        SOURCE: "./"
        REMOTE_HOST: ${{ secrets.FTP_HOST }}
        REMOTE_USER: ${{ secrets.FTP_USERNAME }}
        REMOTE_PORT: ${{ secrets.FTP_PORT }}
        TARGET: "htdocs/wp-content/themes/charlies-theme/"
        EXCLUDE: "/node_modules/, /.git/, /.github/, /.DS_Store, /README.md"

    - name: Deployment Status
      if: success()
      run: |
        echo "✅ Theme deployed successfully!"
        echo "🌐 Check your WordPress site to verify deployment"